version: '3.8'

services:
  app:
    image: lincoln1000/facelift-backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: ${MONGO_URI}